exports.ProductInsertionType = {
  BY_ID: "byId",
  BY_KEYWORD: "byKeyword",
  BY_URL: "byUrl",
  BY_CATEGORY: "byCategory",
};

exports.ProductListingStatus = {
  READY_TO_BE_LISTED: "ready to list",
  LIVE: "live",
  FAILED: "failed",
};

exports.UserType = {
  SELLER: "seller",
  BUYER: "buyer",
};

exports.PackageTypes = {
  LETTER: "LETTER",
  BULKY_GOODS: "BULKY_GOODS",
  CARAVAN: "CARAVAN",
  CARS: "CARS",
  EUROPALLET: "EUROPALLET",
  EXPANDABLE_TOUGH_BAGS: "EXPANDABLE_TOUGH_BAGS",
  EXTRA_LARGE_PACK: "EXTRA_LARGE_PACK",
  FURNITURE: "FURNITURE",
  INDUSTRY_VEHICLES: "INDUSTRY_VEHICLES",
  LARGE_CANADA_POSTBOX: "LARGE_CANADA_POSTBOX",
  LARGE_CANADA_POST_BUBBLE_MAILER: "LARGE_CANADA_POST_BUBBLE_MAILER",
  LARGE_ENVELOPE: "LARGE_ENVELOPE",
  MAILING_BOX: "MAILING_BOX",
  MEDIUM_CANADA_POST_BOX: "MEDIUM_CANADA_POST_BOX",
  MEDIUM_CANADA_POST_BUBBLE_MAILER: "MEDIUM_CANADA_POST_BUBBLE_MAILER",
  MOTORBIKES: "MOTORBIKES",
  ONE_WAY_PALLET: "ONE_WAY_PALLET",
  PACKAGE_THICK_ENVELOPE: "PACKAGE_THICK_ENVELOPE",
  PADDED_BAGS: "PADDED_BAGS",
  PARCEL_OR_PADDED_ENVELOPE: "PARCEL_OR_PADDED_ENVELOPE",
  ROLL: "ROLL",
  SMALL_CANADA_POST_BOX: "SMALL_CANADA_POST_BOX",
  SMALL_CANADA_POST_BUBBLE_MAILER: "SMALL_CANADA_POST_BUBBLE_MAILER",
  TOUGH_BAGS: "TOUGH_BAGS",
  UPS_LETTER: "UPS_LETTER",
  USPS_FLAT_RATE_ENVELOPE: "USPS_FLAT_RATE_ENVELOPE",
  USPS_LARGE_PACK: "USPS_LARGE_PACK",
  VERY_LARGE_PACK: "VERY_LARGE_PACK",
  WINE_PAK: "WINE_PAK",
};

exports.Units = {
  INCH: "INCH",
  FEET: "FEET",
  CENTIMETER: "CENTIMETER",
  METER: "METER",
};

exports.WeightUnits = {
  POUND: "POUND",
  KILOGRAM: "KILOGRAM",
  OUNCE: "OUNCE",
  GRAM: "GRAM",
};

exports.HistoryStatus = {
  INPROGRESS : 'inprogress',
  COMPLETED : 'completed',
}


exports.BulkActionType = {
  CREATE_CATALOGUE: 'create catalogue',
  UPDATE_CATALOGUE: 'update catalogue',
  COPY_CATALOGUE: 'copy catalogue',
  UPDATE_ISKU:'update isku',
  UPDATE_PRICE_AND_QUANTITY: 'update price and quantity',
  BULK_PRODUCT_FETCH: 'bulk product fetch',
}